// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE0R6LHjENSg6MelxIZVwMdqxqmTdwqQE',
    appId: '1:285017546439:web:0569e7034e0acaf7b5e8e2',
    messagingSenderId: '285017546439',
    projectId: 'uni-semester-project',
    authDomain: 'uni-semester-project.firebaseapp.com',
    storageBucket: 'uni-semester-project.firebasestorage.app',
    measurementId: 'G-7HBPQGBJLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRpmwXwoU8E5J14ui6HekRbndpGO8jIuE',
    appId: '1:285017546439:android:a87b8ccc526224eab5e8e2',
    messagingSenderId: '285017546439',
    projectId: 'uni-semester-project',
    storageBucket: 'uni-semester-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPhYbXR4SWEvGpWftDV43FSPnAd7LEeU',
    appId: '1:285017546439:ios:06c15f0bbb8600b2b5e8e2',
    messagingSenderId: '285017546439',
    projectId: 'uni-semester-project',
    storageBucket: 'uni-semester-project.firebasestorage.app',
    iosBundleId: 'com.example.crateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByPhYbXR4SWEvGpWftDV43FSPnAd7LEeU',
    appId: '1:285017546439:ios:06c15f0bbb8600b2b5e8e2',
    messagingSenderId: '285017546439',
    projectId: 'uni-semester-project',
    storageBucket: 'uni-semester-project.firebasestorage.app',
    iosBundleId: 'com.example.crateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE0R6LHjENSg6MelxIZVwMdqxqmTdwqQE',
    appId: '1:285017546439:web:a8aaca0b4fe704ddb5e8e2',
    messagingSenderId: '285017546439',
    projectId: 'uni-semester-project',
    authDomain: 'uni-semester-project.firebaseapp.com',
    storageBucket: 'uni-semester-project.firebasestorage.app',
    measurementId: 'G-EQ9KQS4S5E',
  );
}
